pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        // Checkout the code
        checkout scm

        // Build and run Java program
        sh 'mvn clean install'
        sh 'java -cp target/hello-world-1.0-SNAPSHOT.jar com.example.HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        // Front-end build steps (for example, React or Angular)
        sh 'npm install'
      }
    }
  }
}
